#!/bin/sh /etc/rc.common

USE_PROCD=1
START=96
STOP=10

SERVICE_DIR=/lotusemmc/lanmihome
SERVICE_PY="$SERVICE_DIR/lanmihome.py"
SERVICE_CONFIG="$SERVICE_DIR/config.json"
SERVICE_PYTHONPATH="/lotusemmc/miot/python:$SERVICE_DIR"

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/python3 "$SERVICE_PY" --config "$SERVICE_CONFIG"
    procd_set_param env PYTHONPATH="$SERVICE_PYTHONPATH"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    stop
    start
}
